<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MDC-Alexeid-M" failures="3" tests="11" name="pizdec" time="0.204" errors="0" timestamp="2024-06-12T23:04:04 EEST">
  <testcase classname="student.examples.DeviceIdentificationTest" name="testNegativeID" time="0.005"/>
  <testcase classname="student.examples.HasBatteryTest" name="testOverDischarge" time="0.0"/>
  <testcase classname="student.examples.HasBatteryTest" name="testOvercharge" time="0.002"/>
  <testcase classname="student.examples.HasPowerStatesTest" name="testIsOn" time="0.012"/>
  <testcase classname="student.examples.HasPowerStatesTest" name="testSwitchOn" time="0.001"/>
  <testcase classname="student.examples.HasPowerStatesTest" name="testSwitchoff" time="0.002"/>
  <testcase classname="student.examples.IterativeChargeTest" name="testChargeXML" time="0.003">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;o&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: "o"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:662)
at java.base/java.lang.Integer.parseInt(Integer.java:778)
at student.examples.IterativeChargeTest.testChargeXML(IterativeChargeTest.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testChargeXML -->
  <testcase classname="student.examples.IterativeChargeTest" name="testChargeXML" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [0] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [5]
at student.examples.IterativeChargeTest.testChargeXML(IterativeChargeTest.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testChargeXML -->
  <testcase classname="student.examples.IterativeChargeTest" name="testChargeXML" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [5] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [10]
at student.examples.IterativeChargeTest.testChargeXML(IterativeChargeTest.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testChargeXML -->
  <testcase classname="student.examples.IterativeChargeTest" name="testChargeXML" time="0.0"/>
  <testcase classname="student.examples.IterativeChargeTest" name="testChargeXML" time="0.0"/>
</testsuite> <!-- pizdec -->
